#include "lib.h"
#include "stdio.h"

int main() {
  register float fx asm("fs2");
  register float fy asm("fs3");
  register float fz asm("fs4");
  register float fw asm("fs5");

  register long xx asm("s2");
  register long xy asm("s3");
  register long xz asm("s4");
  register long xw asm("s5");
  asm("addi sp, sp, -32;"
      "li %[xx], 1;"
      "li %[xy], 2;"
      "li %[xz], 3;"
      "li %[xw], 4;"
      "fcvt.s.w %[fx], %[xx];"
      "fcvt.s.w %[fy], %[xy];"
      "fcvt.s.w %[fz], %[xz];"
      "fcvt.s.w %[fw], %[xw];"
      "fsw %[fx], 0(sp);"
      "fsw %[fy], 4(sp);"
      "fsw %[fz], 8(sp);"
      "fsw %[fw], 12(sp);"
      "sw %[xx], 16(sp);"
      "sw %[xy], 20(sp);"
      "sw %[xz], 24(sp);"
      "sw %[xw], 28(sp);"

      "sub %[xx], %[xy], %[xz];"
      "sw %[xy],16(sp);"
      "fmadd.s %[fx], %[fz], %[fw], %[fz];"
      "fsub.s %[fz], %[fy], %[fz];"
      "sub %[xz], %[xw], %[xz];"
      "fsub.s %[fx], %[fy], %[fw];"
      "mul %[xz], %[xx], %[xz];"
      "fsw %[fy],8(sp);"
      "fsub.s %[fw], %[fz], %[fz];"
      "fdiv.s %[fy], %[fz], %[fy];"
      "fdiv.s %[fx], %[fx], %[fz];"
      "fsw %[fy],4(sp);"
      "lw %[xx],28(sp);"
      "fmsub.s %[fx], %[fx], %[fx], %[fz];"
      "fsub.s %[fw], %[fz], %[fz];"
      "fsw %[fw],0(sp);"
      "add %[xw], %[xy], %[xz];"
      "flw %[fy],12(sp);"
      "fadd.s %[fw], %[fy], %[fy];"
      "flw %[fz],8(sp);"
      "sub %[xz], %[xx], %[xy];"
      "lw %[xw],28(sp);"
      "fsw %[fw],0(sp);"
      "fmadd.s %[fy], %[fz], %[fx], %[fy];"
      "fsw %[fx],12(sp);"
      "lw %[xx],16(sp);"
      "fsub.s %[fw], %[fy], %[fz];"
      "lw %[xz],28(sp);"
      "fadd.s %[fw], %[fz], %[fz];"
      "sub %[xz], %[xz], %[xw];"
      "fmadd.s %[fx], %[fy], %[fx], %[fw];"
      "fadd.s %[fy], %[fz], %[fx];"
      "fsw %[fx],4(sp);"
      "sw %[xz],20(sp);"
      "fdiv.s %[fy], %[fw], %[fw];"
      "fsw %[fz],4(sp);"
      "fsw %[fy],12(sp);"
      "fdiv.s %[fz], %[fy], %[fy];"
      "fmsub.s %[fx], %[fx], %[fx], %[fx];"
      "fadd.s %[fy], %[fw], %[fz];"
      "fdiv.s %[fy], %[fy], %[fy];"
      "fsw %[fy],4(sp);"
      "fsub.s %[fz], %[fz], %[fy];"
      "fsw %[fx],0(sp);"
      "fsw %[fz],0(sp);"
      "fsw %[fy],12(sp);"
      "add %[xw], %[xx], %[xx];"
      "sub %[xw], %[xz], %[xw];"
      "fsw %[fx],8(sp);"
      "fsw %[fw],12(sp);"
      "fdiv.s %[fy], %[fz], %[fy];"
      "fsw %[fx],4(sp);"
      "mul %[xw], %[xz], %[xz];"
      "fadd.s %[fy], %[fy], %[fz];"
      "mul %[xx], %[xz], %[xy];"
      "sw %[xy],20(sp);"
      "fsub.s %[fy], %[fx], %[fx];"
      "fsw %[fy],8(sp);"
      "add %[xy], %[xw], %[xy];"
      "fadd.s %[fy], %[fy], %[fw];"
      "add %[xz], %[xx], %[xz];"
      "sub %[xw], %[xz], %[xx];"
      "add %[xy], %[xx], %[xz];"
      "fsub.s %[fz], %[fz], %[fy];"
      "fsw %[fw],12(sp);"
      "fadd.s %[fz], %[fx], %[fy];"
      "fsw %[fz],8(sp);"
      "flw %[fy],4(sp);"
      "fmsub.s %[fz], %[fw], %[fz], %[fy];"
      "fsw %[fw],0(sp);"
      "fsw %[fy],8(sp);"
      "fdiv.s %[fw], %[fw], %[fz];"
      "fsw %[fx],12(sp);"
      "add %[xw], %[xx], %[xx];"
      "add %[xz], %[xx], %[xz];"
      "lw %[xx],28(sp);"
      "flw %[fx],12(sp);"
      "fsub.s %[fw], %[fw], %[fx];"
      "mul %[xz], %[xz], %[xz];"
      "fsub.s %[fw], %[fy], %[fz];"
      "fadd.s %[fy], %[fy], %[fy];"
      "fdiv.s %[fx], %[fy], %[fw];"
      "fsw %[fx],12(sp);"
      "sub %[xw], %[xw], %[xy];"
      "add %[xx], %[xy], %[xw];"
      "fsw %[fz],12(sp);"
      "fsw %[fy],4(sp);"
      "fadd.s %[fw], %[fx], %[fz];"
      "fdiv.s %[fw], %[fz], %[fy];"
      "fsw %[fz],4(sp);"
      "fadd.s %[fy], %[fy], %[fz];"
      "sw %[xw],16(sp);"
      "fsw %[fx],12(sp);"
      "fsw %[fy],0(sp);"
      "flw %[fw],4(sp);"
      "lw %[xx],24(sp);"
      "fsub.s %[fz], %[fx], %[fz];"
      "fdiv.s %[fy], %[fx], %[fz];"
      "fmsub.s %[fx], %[fy], %[fw], %[fx];"
      "fsw %[fw],12(sp);"
      "fadd.s %[fw], %[fz], %[fz];"
      "fdiv.s %[fz], %[fx], %[fy];"
      "fsw %[fz],0(sp);"
      "sub %[xw], %[xw], %[xy];"
      "fsw %[fx],4(sp);"
      "fsub.s %[fz], %[fy], %[fy];"
      "fadd.s %[fw], %[fz], %[fx];"
      "fmsub.s %[fx], %[fw], %[fy], %[fy];"
      "add %[xy], %[xy], %[xy];"
      "fmsub.s %[fy], %[fy], %[fx], %[fz];"
      "fsw %[fw],4(sp);"
      "fsw %[fw],0(sp);"
      "flw %[fy],8(sp);"
      "fsub.s %[fw], %[fx], %[fw];"
      "fmsub.s %[fz], %[fy], %[fz], %[fz];"
      "fadd.s %[fx], %[fw], %[fw];"
      "mul %[xy], %[xy], %[xy];"
      "fsub.s %[fw], %[fw], %[fz];"
      "fsw %[fy],12(sp);"
      "lw %[xy],24(sp);"
      "fsub.s %[fz], %[fz], %[fw];"
      "fsub.s %[fw], %[fw], %[fy];"
      "fdiv.s %[fz], %[fx], %[fz];"
      "add %[xw], %[xz], %[xz];"
      "fdiv.s %[fz], %[fz], %[fz];"
      "fmadd.s %[fy], %[fw], %[fx], %[fy];"
      "fdiv.s %[fz], %[fw], %[fx];"
      "lw %[xz],24(sp);"
      "fmadd.s %[fy], %[fz], %[fy], %[fz];"
      "fdiv.s %[fw], %[fz], %[fz];"
      "fsw %[fy],12(sp);"
      "flw %[fx],12(sp);"
      "fdiv.s %[fz], %[fw], %[fw];"
      "fadd.s %[fx], %[fy], %[fy];"
      "fmsub.s %[fw], %[fx], %[fy], %[fx];"
      "lw %[xw],16(sp);"
      "fsub.s %[fy], %[fy], %[fx];"
      "flw %[fx],4(sp);"
      "fsub.s %[fx], %[fw], %[fz];"
      "fsub.s %[fx], %[fx], %[fx];"
      "fsw %[fw],8(sp);"
      "fmadd.s %[fx], %[fy], %[fz], %[fz];"
      "fadd.s %[fx], %[fw], %[fx];"
      "sw %[xw],20(sp);"
      "fadd.s %[fx], %[fx], %[fy];"
      "fdiv.s %[fy], %[fy], %[fx];"
      "fdiv.s %[fz], %[fy], %[fz];"
      "add %[xx], %[xw], %[xw];"
      "lw %[xw],28(sp);"
      "mul %[xz], %[xz], %[xz];"
      "sub %[xz], %[xw], %[xz];"
      "fsw %[fw],8(sp);"
      "fadd.s %[fx], %[fw], %[fx];"
      "lw %[xw],28(sp);"
      "fsub.s %[fw], %[fx], %[fw];"
      "fadd.s %[fz], %[fw], %[fy];"
      "fsub.s %[fw], %[fy], %[fz];"
      "lw %[xz],24(sp);"
      "fsw %[fy],12(sp);"
      "add %[xx], %[xx], %[xz];"
      "flw %[fz],12(sp);"
      "mul %[xz], %[xz], %[xx];"
      "fsw %[fx],12(sp);"
      "fsw %[fz],8(sp);"
      "flw %[fz],8(sp);"
      "flw %[fz],12(sp);"
      "mul %[xz], %[xw], %[xy];"
      "sw %[xx],24(sp);"
      "fmsub.s %[fw], %[fz], %[fx], %[fx];"
      "fmadd.s %[fw], %[fx], %[fz], %[fz];"
      "fsw %[fz],8(sp);"
      "fadd.s %[fy], %[fx], %[fz];"
      "fadd.s %[fw], %[fw], %[fz];"
      "fsw %[fy],0(sp);"
      "fsub.s %[fz], %[fy], %[fx];"
      "sub %[xw], %[xw], %[xx];"
      "add %[xy], %[xy], %[xx];"
      "fsw %[fz],0(sp);"
      "lw %[xx],24(sp);"
      "lw %[xy],28(sp);"
      "fsub.s %[fw], %[fx], %[fy];"
      "sw %[xy],20(sp);"
      "flw %[fx],0(sp);"
      "lw %[xw],20(sp);"
      "fdiv.s %[fy], %[fz], %[fw];"
      "fmsub.s %[fx], %[fy], %[fx], %[fz];"
      "mul %[xw], %[xy], %[xy];"
      "mul %[xz], %[xw], %[xy];"
      "add %[xx], %[xz], %[xz];"
      "sub %[xy], %[xw], %[xx];"
      "lw %[xz],16(sp);"
      "mul %[xx], %[xz], %[xw];"
      "fsw %[fz],4(sp);"
      "fmadd.s %[fy], %[fw], %[fz], %[fz];"
      "sub %[xz], %[xw], %[xx];"
      "add %[xw], %[xx], %[xy];"
      "fsw %[fz],12(sp);"
      "fsw %[fx],4(sp);"
      "add %[xz], %[xw], %[xy];"
      "fmadd.s %[fy], %[fy], %[fw], %[fz];"

      "addi sp, sp, 32"
      : [fx] "+f"(fx), [fy] "+f"(fy), [fz] "+f"(fz), [fw] "+f"(fw),
        [xx] "+r"(xx), [xy] "+r"(xy), [xz] "+r"(xz), [xw] "+r"(xw));
  print_f(fx);
  print_c('\n');
  print_f(fy);
  print_c('\n');
  print_f(fz);
  print_c('\n');
  print_f(fw);
  print_c('\n');
  print_d(xx);
  print_c('\n');
  print_d(xy);
  print_c('\n');
  print_d(xz);
  print_c('\n');
  print_d(xw);
  print_c('\n');

  exit_proc();
}